container:
  image: ruby:2.7.1

test_task:
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script:
      - echo $RUBY_VERSION
      - cat Gemfile.lock
    populate_script: bundle install
  test_script: bundle exec rake test
