---
AllCops:
  TargetRubyVersion: 2.7

Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100
Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Metrics/BlockLength:
  Exclude:
    - test/**/*_test.rb
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Naming/FileName:
  Enabled: false
Naming/PredicateName:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/PerlBackrefs:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"
Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
